# Generated by Django 4.0.3 on 2022-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_index', models.BooleanField(default=False)),
                ('edit_about_page', models.BooleanField(default=False)),
                ('edit_subscription', models.BooleanField(default=False)),
                ('create_subscription', models.BooleanField(default=False)),
                ('response_to_feedback', models.BooleanField(default=False)),
                ('change_profiles_info', models.BooleanField(default=False)),
                ('change_profile_group', models.BooleanField(default=False)),
                ('edit_forums', models.BooleanField(default=False)),
                ('create_forums', models.BooleanField(default=False)),
                ('edit_posts', models.BooleanField(default=False)),
            ],
        ),
    ]
