# Generated by Django 4.0.3 on 2022-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffgroup',
            name='title',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
    ]
