# Generated by Django 4.0.3 on 2022-03-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('ESP', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('custom_ESP', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('lines', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('stats_calculator', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('match_up_calculator', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('autoplay', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('complete_quests', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
                ('advanced_in_depth_gameplay', models.BooleanField(choices=[(False, False), (True, True)], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.features')),
            ],
        ),
    ]
