# Generated by Django 4.0.3 on 2022-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='ESP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='advanced_in_depth_gameplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='complete_quests',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='custom_ESP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='lines',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='match_up_calculator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='stats_calculator',
            field=models.BooleanField(default=False),
        ),
    ]
