# Generated by Django 4.0.3 on 2022-04-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_features_esp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
