# Generated by Django 4.0.3 on 2022-04-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
