# Generated by Django 4.0.3 on 2022-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_profile_picture_subscription_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=1)),
            ],
        ),
    ]
