# Generated by Django 4.0.3 on 2022-04-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0001_initial'),
        ('manage_profiles', '0003_contactus_image_contactus_status_contactus_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='staff_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrate.staffgroup'),
        ),
    ]
