# Generated by Django 4.0.3 on 2022-04-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrate', '0002_staffgroup_title'),
        ('manage_profiles', '0004_contactus_staff_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='staff_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrate.staffgroup'),
        ),
    ]
