# Generated by Django 4.0.3 on 2022-04-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0005_remove_contactus_staff_group_profile_staff_group'),
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreply',
            name='feedback',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='manage_profiles.contactus'),
            preserve_default=False,
        ),
    ]
