# Generated by Django 4.0.3 on 2022-04-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_profiles', '0005_remove_contactus_staff_group_profile_staff_group'),
        ('user_activity', '0003_alter_feedbackreply_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreply',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_profiles.contactus'),
        ),
    ]
