# Generated by Django 4.0.3 on 2022-04-10 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0004_alter_feedbackreply_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
