# Generated by Django 4.0.3 on 2022-04-12 10:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
