# Generated by Django 4.0.3 on 2022-04-12 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_comment_date_alter_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=600, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
