# Generated by Django 4.0.3 on 2022-03-29 12:20

import django.core.validators
from django.db import migrations, models
import pyla.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPylaPageConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_pyla_text', models.TextField()),
                ('goals_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutPylaTextConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_pyla_text', models.TextField()),
                ('goals_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexConfigurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyla_moto', models.TextField(max_length=70, validators=[django.core.validators.MinLengthValidator(25)])),
                ('pyla_img', models.ImageField(blank=True, null=True, upload_to='', validators=[pyla.web.validators.disable_editing])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
