# Generated by Django 4.0.3 on 2022-03-29 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexconfigurator',
            name='pyla_moto',
            field=models.TextField(max_length=70, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
